- name: Update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Disable swap temporarily
  command: swapoff -a

- name: Disable swap permanently in fstab
  replace:
    path: /etc/fstab
    regexp: '^.*swap.img.*$'
    replace: '# \g<0>'

- name: Enable IP forwarding
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1

- name: Apply sysctl
  command: sysctl --system

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Persist module load
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter

- name: Set sysctl parameters for Kubernetes networking
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
    - { name: 'net.ipv4.ip_forward', value: 1 }
